[project]
name = "langchain-infinispan"
version = "0.1.0"
description = "An integration package connecting Infinispan and LangChain"
authors = [{ name = "Infinispan" }]
readme = "README.md"
license = { text = "Apache-2.0" }
requires-python = ">=3.10,<4.0"
dependencies = [
    "langchain-core>=1.2.5,<2.0.0",
    "requests>=2.28.0,<3.0.0",
]

[project.urls]
"Source Code" = "https://github.com/infinispan/langchain-infinispan"
repository = "https://github.com/infinispan/langchain-infinispan"

[dependency-groups]
test = [
    "pytest>=7.3,<9.0",
    "pytest-mock>=3.10.0",
    "pytest-asyncio>=0.21.1,<1.4.0",
]
lint = ["ruff>=0.1.5,<0.16.0"]
typing = ["mypy>=0.991,<1.20"]
test_integration = ["langchain-tests>=1.1.6,<2.0.0"]

[tool.ruff.lint]
select = [
  "E",  # pycodestyle
  "F",  # pyflakes
  "I",  # isort
]

[tool.mypy]
disallow_untyped_defs = "True"

[tool.coverage.run]
omit = ["tests/*"]

[tool.pytest.ini_options]
addopts = "--strict-markers --strict-config --durations=5"
asyncio_mode = "auto"
markers = [
  "requires: mark tests as requiring a specific library",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
